In [5]:
import numpy as np
import hashlib
import time
import matplotlib.pyplot as plt


def hashMd(x):
    t=str(x)
    result = hashlib.md5(t.encode()) 
    # printing the equivalent hexadecimal value. 
    print("The hexadecimal hash of PlainText is equivalent: ", end ="") 
    print(result.hexdigest()) 
    
def checkValidity(p,q):
    if hashMd(p) in hashMd(q):
        print("VALID DATA")
    else:
        print("modified")

def gen(x):
    return x.random.randint(1,5, size=(3, 3))

key_gen=gen(np)

public_key =key_gen[:,0]
private_key = np.reciprocal(public_key.astype(np.float32))


#error distribution
def error():
    err=np.random.uniform(1,3, size=(3))
    return err
err=error()
err=err.astype(int)
print("error",err)


#encryption 

def encryption(x):
    cipher=x*public_key+err
    return cipher


#decryption

def decryption(x):
    decipher= x*private_key-err
    return decipher.round()

    

print(key_gen)

print("public_key",key_gen[:,0])

start = time.time()
print("private_Key",private_key)
smart = np.loadtxt('mytext.txt')
smart = smart.reshape((188,3))
smart=smart.round()
#np.savetxt('mytext.txt',smart,fmt='%-7.2f')

print("\n======plainText======\n",smart)
print("\n===hashOfplainTextI======\n")
hashMd(smart)

print("size of PlainText=",smart.shape)

cipher=encryption(smart)


print("\n======cipherText======\n",cipher)
print("size of cipher=",cipher.shape)
dicipher=decryption(cipher)

print("\n======decipherText======\n",dicipher)
print("size of decipher=",dicipher.shape)
end = time.time()
totalTime=end-start
print("total time taken====((((",round(totalTime,3),"))))")

error [1 1 2]
[[4 1 2]
 [1 2 1]
 [2 4 2]]
public_key [4 1 2]
private_Key [0.25 1.   0.5 ]

======plainText======
 [[  1018.   6013.   6296.]
 [  4840.  12855.  34517.]
 [ 36206.  29872.   1455.]
 [ 33772.   1498.   3888.]
 [  7521.  12621.   9138.]
 [ 10754.   1269.    480.]
 [  1774.   2092.  36400.]
 [   751.   1755.  13250.]
 [  5032.   7080.   1051.]
 [   324.   3688.   9724.]
 [  1593.  14695.   9026.]
 [ 22910.  35357.   2137.]
 [  6098.   6948.   5652.]
 [  5800.  12206.    699.]
 [   744.  33286.  30551.]
 [ 13263.    812.  32250.]
 [  1388.  27618.   5256.]
 [   999.    626.   1263.]
 [  3618.  39807.  18082.]
 [ 36263.   2517.   3611.]
 [ 11677.   4531.  40755.]
 [ 25604.  28650.   7393.]
 [ 31739.   4592.   1517.]
 [  1660.  23427.  47385.]
 [ 10533.   1612.    460.]
 [ 12131.   1104.    808.]
 [ 12526.   1097.   1867.]
 [ 11030.  12054.   3163.]
 [  9328.   3891.    866.]
 [  1006.   4864.   1155.]
 [ 36878.  25265.   2822.]
 [   676.   2061.  49437.]
 [ 22392.   2671.   98