In [1]:
from fractions import Fraction
from typing import List, Sequence
import numpy as np
import matplotlib.pyplot as plt
import time
import pandas as pd


#==============================LLL-Algorithm==============================================
class Vector(list):
    def __init__(self, x):
        super().__init__(map(Fraction, x))

    def sdot(self) -> Fraction:
        return self.dot(self)

    def dot(self, rhs: "Vector") -> Fraction:
        """
        >>> Vector([1, 2, 3]).dot([4, 5, 6])
        Fraction(32, 1)
        """
        rhs = Vector(rhs)
        assert len(self) == len(rhs)
        return sum(map(lambda x: x[0] * x[1], zip(self, rhs)))

    def proj_coff(self, rhs: "Vector") -> Fraction:
        """
        >>> Vector([1, 1, 1]).proj_coff([-1, 0, 2])
        Fraction(1, 3)
        """
        rhs = Vector(rhs)
        assert len(self) == len(rhs)
        return self.dot(rhs) / self.sdot()

    def proj(self, rhs: "Vector") -> "Vector":
        """
        >>> Vector([1, 1, 1]).proj([-1, 0, 2])
        [1/3, 1/3, 1/3]
        """
        rhs = Vector(rhs)
        assert len(self) == len(rhs)
        return self.proj_coff(rhs) * self

    def __sub__(self, rhs: "Vector") -> "Vector":
        """
        >>> Vector([1, 2, 3]) - [6, 5, 4]
        [-5, -3, -1]
        """
        rhs = Vector(rhs)
        assert len(self) == len(rhs)
        return Vector(x - y for x, y in zip(self, rhs))

    def __mul__(self, rhs: Fraction) -> "Vector":
        """
        >>> Vector(["3/2", "4/5", "1/4"]) * 2
        [3, 8/5, 1/2]
        """
        return Vector(x * rhs for x in self)

    def __rmul__(self, lhs: Fraction) -> "Vector":
        """
        >>> 2 * Vector(["3/2", "4/5", "1/4"])
        [3, 8/5, 1/2]
        """
        return Vector(x * lhs for x in self)

    def __repr__(self) -> str:
        return "[{}]".format(", ".join(str(x) for x in self))


def gramschmidt(v: Sequence[Vector]) -> Sequence[Vector]:
    """
    >>> gramschmidt([[3, 1], [2, 2]])
    [[3, 1], [-2/5, 6/5]]
    >>> gramschmidt([[4, 1, 2], [4, 7, 2], [3, 1, 7]])
    [[4, 1, 2], [-8/7, 40/7, -4/7], [-11/5, 0, 22/5]]
    """
    u: List[Vector] = []
    for vi in v:
        ui = Vector(vi)
        for uj in u:
            ui = ui - uj.proj(vi)

        if any(ui):
            u.append(ui)
    return u


def reduction(basis: Sequence[Sequence[int]], delta: float) -> Sequence[Sequence[int]]:
    """
    >>> reduction([[1, 1, 1], [-1, 0, 2], [3, 5, 6]], 0.75)
    [[0, 1, 0], [1, 0, 1], [-1, 0, 2]]
    >>> reduction([[105, 821, 404, 328], [881, 667, 644, 927], [181, 483, 87, 500], [893, 834, 732, 441]], 0.75)
    [[76, -338, -317, 172], [88, -171, -229, -314], [269, 312, -142, 186], [519, -299, 470, -73]]
    """
    n = len(basis)
    basis = list(map(Vector, basis))
    ortho = gramschmidt(basis)

    def mu(i: int, j: int) -> Fraction:
        return ortho[j].proj_coff(basis[i])

    k = 1
    while k < n:
        for j in range(k - 1, -1, -1):
            mu_kj = mu(k, j)
            if abs(mu_kj) > 0.5:
                basis[k] = basis[k] - basis[j] * round(mu_kj)
                ortho = gramschmidt(basis)

        if ortho[k].sdot() >= (delta - mu(k, k - 1)**2) * ortho[k - 1].sdot():
            k += 1
        else:
            basis[k], basis[k - 1] = basis[k - 1], basis[k]
            ortho = gramschmidt(basis)
            k = max(k - 1, 1)

    return [list(map(int, b)) for b in basis]


#import olll
#[[1, 1, 1],[-1, 0, 2],[3, 5, 6]]
reduced_basis =reduction([
    [1, 1, 1],
    [1, 0, 2 ],
    [3, 5, 6],
], 0.75)

basis=np.array(reduced_basis)
basis=basis+3
CC_pk=basis[:,0]
CC_sk = np.reciprocal(CC_pk.astype(np.float32))
print(CC_sk)

#print(reduced_basis)
# [[0, 1, 0], [1, 0, 1], [-1, 0, 2]]



#reduced_basis =np.array(reduced_basis)
print(basis)
class SM:
    
    noOfmeters=0
    def __init__(self,text):
        self.text=text
        SM.noOfmeters+=1
        print("===========READING FOR THE SMART METER==========(AP-",SM.noOfmeters,')')
        print("===========PlainText==========",self.text)
        
        def hashMd(self):
            t=str(self.ptext)
            result = hashlib.md5(t.encode()) 
            # printing the equivalent hexadecimal value. 
            print("The hexadecimal equivalent of hash is : ", end ="") 
            print(result.hexdigest()) 
            return result
         
         
    def error(self):
        err=np.random.uniform(1,3, size=(3))
        return err
        err=error()
        err=err.astype(int)
        print("error",err)

    
        
    def encryption(self,pk):
        c=self.text*pk
        print("======ENCRYPTED READING FROM THE SMART METER==========(AP-",SM.noOfmeters,')')
        return c

class BS:
    pass
        
        
class CC(SM):
    
    def __init__(self,text):
        self.text=text
        
        #========================DE-CRYPTION FUNCTION==========================
        
  
    
#REDUUCTION OF BASIS
#[[1, 1, 1],[-1, 0, 2],[3, 5, 6]]
reduced_basis =reduction([
    [1, 1, 1],
    [1, 0, 2 ],
    [3, 5, 6],
], 0.75)

basis=np.array(reduced_basis)
basis=basis+3
CC_pk=basis[:,0]
print("CC's Public key vector : ==",CC_pk)
CC_sk = np.reciprocal(CC_pk.astype(np.float32))
print("CC's Private key vector : ==",CC_sk)

#print(reduced_basis)
# [[0, 1, 0], [1, 0, 1], [-1, 0, 2]]




CC_sk1=CC_sk[0]
key_1=CC_pk[0]
key_2=CC_pk[1]
key_3=CC_pk[2]


data2=np.loadtxt('homeA-meter2_2014.txt')
print(data2)
print("data shape===",data2.shape)

dataAps123=data2[:,0:3]
print(dataAps123.shape)
dataAps456=data2[:,3:6]
print(dataAps456.shape)
dataAps789=data2[:,6:9]
print(dataAps789.shape)
dataAps91011=data2[:,9:11]
print(dataAps91011.shape)
np.around(dataAps91011,4)
print("data",data2)

data_1 = np.loadtxt('mytext1.txt')
data = data_1.reshape((188,3))
data=data.round()
Ap_1=data2[:,0]
Ap_2=data2[:,1]
Ap_3=data2[:,2]

start = time.time()
sm1=SM(meter_1)
print(sm1.text)
c1=sm1.encryption(key_1)
print(c1)
end = time.time()
totalTime=end-start
print("total time taken====((((",round(totalTime,3),"))))")
start = time.time()
cc1=CC(c1)
print(cc1.decryption(CC_sk1))

end = time.time()
totalTime=end-start
print("total time taken====((((",round(totalTime,4),"))))")







[0.33333334 0.25       1.        ]
[[3 2 4]
 [4 4 4]
 [1 3 4]]
CC's Public key vector : == [3 4 1]
CC's Private key vector : == [0.33333334 0.25       1.        ]
[[1.95337778e-01 8.32044440e-02 5.68611100e-03 ... 1.95337778e-01
  1.95337778e-01 1.95337778e-01]
 [1.82158333e-01 3.61388890e-02 5.67888900e-03 ... 1.82158333e-01
  1.82158333e-01 1.82158333e-01]
 [1.34808333e-01 4.70338890e-02 5.63500000e-03 ... 1.34808333e-01
  1.34808333e-01 1.34808333e-01]
 ...
 [1.48785000e-01 7.21694440e-02 1.56111000e-04 ... 1.48785000e-01
  1.48785000e-01 1.48785000e-01]
 [5.42638890e-02 2.79038890e-02 4.72220000e-05 ... 5.42638890e-02
  5.42638890e-02 5.42638890e-02]
 [1.70284444e-01 5.61450000e-02 1.53889000e-04 ... 1.70284444e-01
  1.70284444e-01 1.70284444e-01]]
data shape=== (17520, 16)
(17520, 3)
(17520, 3)
(17520, 3)
(17520, 2)
data [[1.95337778e-01 8.32044440e-02 5.68611100e-03 ... 1.95337778e-01
  1.95337778e-01 1.95337778e-01]
 [1.82158333e-01 3.61388890e-02 5.67888900e-03 ... 1.82158333e-

NameError: name 'meter_1' is not defined